### ISSUE TITLE
About pre-built BESS binaries

### ISSUE THREAD

**Issue by s5uishida** [omec-project/bess#64]
Hi,

I can't find any pre-built BESS binaries in the link ([Release](https://github.com/omec-project/bess/releases/latest)) in this repository. Where can I get this?
```
...
To install BESS on Linux quickly, you can download the binary from Release.
Please refer to GCC x86 Options to determine which tarball to use. Suppose bess-core2-linux.tar.gz is downloaded:
...
```

**Comment by gab-arrobo** [comment]
Hi @s5uishida,

Sorry for the misleading information. I just opened #65 to remove that. FYI, we only create/release a "base" Docker image that is used as part of the [upf](https://github.com/omec-project/upf). You can download the latest BESS binary from the [upstream repo](https://github.com/NetSys/bess/releases/tag/v0.4.0)
